"""
Pictures for MECE Insights articles.

Owner, 2026-10-06: "add photos", "if image generation is needed, use Gemini only", then "or take open source photos
strictly related to the topic". So each picture slot (a hero and up to two inline) is filled in this order
(DAILY_BLOG_PICTURES, default "photos,gemini"):

  photos   a real photograph under an open licence that allows commercial use and resizing (CC0, public domain,
           CC BY, CC BY-SA), found on Wikimedia Commons and Openverse with the writer's search queries (named
           places, companies, products, activities), then judged by a Gemini vision model against the article: it
           must show the subject itself, not something generic; logos, maps, charts, screenshots, text-heavy images
           and close-up portraits are rejected. Credited under the picture: creator, source, licence, with links.
  gemini   generated by a Gemini image model (DAILY_BLOG_IMAGE_MODEL, else the newest gemini-*image* model the key
           lists, else gemini-2.5-flash-image) in one house style: documentary editorial photo, India, no text,
           logos or real people. Credited "Image generated with Gemini".

Every picture is resized with Pillow (WebP for the page, a 1200 px JPEG for link previews) and stored in the public
Supabase Storage bucket `insights` (created on first use). Every step degrades: no photo, no model, no bucket or a
failed call means an article without that picture, never a failed article. `diagnose()` reports what works.
"""

from __future__ import annotations

import hashlib
import html as _html
import io
import json
import os
import re
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Callable, Dict, List, Optional

BUCKET = "insights"
HERO_WIDTH = 2000
INLINE_WIDTH = 1600
OG_WIDTH = 1200
CREDIT = "Image generated with Gemini for MECE Insights"
UA = "MECE-Insights/1.0 (+https://mece.in/insights)"

HOUSE_STYLE = (
    "Editorial photograph for a long-form business and economics magazine, in the style of a documentary "
    "photo essay. Set in India. Natural light, real textures, calm and considered composition with negative "
    "space, muted and warm colour palette, shallow depth of field, shot on a 35mm lens. "
    "Strictly no text, no letters, no numbers, no logos, no brand names, no signage with writing, no watermarks, "
    "no recognisable real people or celebrities; any people are anonymous, seen from behind, at a distance or out of focus."
)

_models: Dict[str, Any] = {"at": 0.0, "list": []}
_dead: Dict[str, float] = {}


def picture_order() -> List[str]:
    raw = (os.getenv("DAILY_BLOG_PICTURES") or "photos,gemini").lower()
    out = [x.strip() for x in raw.split(",") if x.strip() in ("photos", "gemini")]
    return out or ["photos", "gemini"]


def available() -> bool:
    """Gemini (generation and the photo judge) is usable."""
    if not (os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")):
        return False
    try:
        import google.genai  # noqa: F401
        return True
    except Exception:
        return False


def _client():
    from google import genai
    return genai.Client(api_key=os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY"))


def _is_gone(e: Exception) -> bool:
    t = f"{type(e).__name__} {e}".lower()
    return any(k in t for k in ("404", "not_found", "not found", "no longer available", "is not supported"))


# ============================================================================ Gemini generation
def image_models() -> List[str]:
    """Gemini image models to try: DAILY_BLOG_IMAGE_MODEL, then what this key lists (newest first)."""
    out: List[str] = []
    env = (os.getenv("DAILY_BLOG_IMAGE_MODEL") or "").strip()
    if env:
        out.append(env.removeprefix("models/"))
    if time.time() - _models["at"] > 3600:
        names: List[str] = []
        try:
            for m in _client().models.list():
                name = (getattr(m, "name", "") or "").removeprefix("models/")
                actions = getattr(m, "supported_actions", None) or []
                if name.startswith("gemini") and "image" in name and (not actions or "generateContent" in actions):
                    names.append(name)
        except Exception as e:  # noqa: BLE001
            print(f"[insights images] model list failed: {type(e).__name__}: {e}")

        def key(n: str):
            m = re.search(r"gemini-(\d+(?:\.\d+)?)", n)
            return (-(float(m.group(1)) if m else 0.0), "preview" in n, "pro" in n)
        _models.update(at=time.time(), list=sorted(dict.fromkeys(names), key=key))
    for n in _models["list"] + ["gemini-2.5-flash-image"]:
        if n not in out:
            out.append(n)
    return [m for m in out if time.time() - _dead.get(m, 0) > 6 * 3600]


def gemini_image(prompt: str, aspect: str = "16:9") -> Dict[str, Any]:
    """{bytes, mime, model} from the first Gemini image model that answers. Raises with every model's error."""
    from google.genai import types
    client = _client()
    errors = []
    for model in image_models():
        attempts = [
            dict(response_modalities=["IMAGE"], image_config=types.ImageConfig(aspect_ratio=aspect)),
            dict(response_modalities=["TEXT", "IMAGE"], image_config=types.ImageConfig(aspect_ratio=aspect)),
            dict(response_modalities=["TEXT", "IMAGE"]),
        ]
        for i, kw in enumerate(attempts):
            try:
                resp = client.models.generate_content(model=model, contents=prompt,
                                                      config=types.GenerateContentConfig(**kw))
                for cand in getattr(resp, "candidates", None) or []:
                    for part in getattr(getattr(cand, "content", None), "parts", None) or []:
                        blob = getattr(part, "inline_data", None)
                        if blob is not None and getattr(blob, "data", None):
                            return {"bytes": blob.data, "mime": getattr(blob, "mime_type", "image/png"), "model": model}
                reason = ""
                fb = getattr(resp, "prompt_feedback", None)
                if fb is not None and getattr(fb, "block_reason", None):
                    reason = f" (blocked: {fb.block_reason})"
                errors.append(f"{model}: no image in the answer{reason}")
                break
            except Exception as e:  # noqa: BLE001
                if _is_gone(e):
                    _dead[model] = time.time()
                    errors.append(f"{model}: not available on this key")
                    break
                if i == len(attempts) - 1:
                    errors.append(f"{model}: {type(e).__name__}: {str(e)[:140]}")
    raise RuntimeError("; ".join(errors)[:600] or "no Gemini image model available")


# ============================================================================ open-licensed photos
_HTTP_TIMEOUT = 12
_BAD_TITLE = re.compile(r"\b(logo|logos|map|maps|flag|coat of arms|emblem|diagram|chart|graph|icon|seal|signature|"
                        r"screenshot|infographic|poster|banner|svg|plan|blueprint|stamp|currency note|document|"
                        r"letter|newspaper|cartoon|illustration|drawing|painting)\b", re.I)


def _http_json(url: str, params: Dict[str, Any]) -> Dict[str, Any]:
    import requests
    r = requests.get(url, params=params, timeout=_HTTP_TIMEOUT, headers={"User-Agent": UA, "Accept": "application/json"})
    r.raise_for_status()
    return r.json()


def _http_bytes(url: str, limit: int = 15_000_000) -> bytes:
    import requests
    with requests.get(url, timeout=20, headers={"User-Agent": UA}, stream=True) as r:
        r.raise_for_status()
        buf = io.BytesIO()
        for chunk in r.iter_content(65536):
            buf.write(chunk)
            if buf.tell() > limit:
                raise ValueError("image too large")
        return buf.getvalue()


def license_ok(name: str) -> bool:
    """Licences that allow commercial use and resizing: CC0, public domain, CC BY, CC BY-SA. Not NC, not ND."""
    t = (name or "").lower().replace("_", " ").replace("-", " ")
    if not t or any(x in t for x in (" nc", "noncommercial", "non commercial", " nd", "noderiv", "no deriv", "fair use",
                                     "all rights", "copyrighted")):
        return False
    return any(x in t for x in ("cc0", "public domain", "pdm", "cc by", "attribution"))


def _strip_html(s: str) -> str:
    return re.sub(r"\s+", " ", _html.unescape(re.sub(r"(?s)<[^>]+>", " ", s or ""))).strip()


def search_commons(query: str, *, http: Callable = _http_json, limit: int = 12) -> List[Dict[str, Any]]:
    data = http("https://commons.wikimedia.org/w/api.php", {
        "action": "query", "format": "json", "generator": "search", "gsrsearch": f"filetype:bitmap {query}",
        "gsrnamespace": 6, "gsrlimit": limit, "prop": "imageinfo", "iiprop": "url|size|mime|extmetadata",
        "iiurlwidth": 1920,  # one of Wikimedia's standard thumbnail widths
    })
    pages = ((data or {}).get("query") or {}).get("pages") or {}
    pages = list(pages.values()) if isinstance(pages, dict) else list(pages)
    pages.sort(key=lambda p: p.get("index", 0))
    out = []
    for p in pages:
        ii = (p.get("imageinfo") or [{}])[0]
        meta = ii.get("extmetadata") or {}
        lic = _strip_html((meta.get("LicenseShortName") or {}).get("value") or "")
        title = re.sub(r"^File:", "", p.get("title") or "").rsplit(".", 1)[0]
        if ii.get("mime") not in ("image/jpeg", "image/png", "image/webp") or not license_ok(lic):
            continue
        if _BAD_TITLE.search(title) or (ii.get("width") or 0) < 900:
            continue
        big = ii.get("thumburl") or ii.get("url") or ""
        thumb = _commons_thumb(ii.get("url") or big, 500)
        out.append({
            "source": "Wikimedia Commons", "title": title, "page_url": ii.get("descriptionurl") or "",
            "image_url": big, "thumb_url": thumb, "width": ii.get("width"), "height": ii.get("height"),
            "license": lic, "license_url": _strip_html((meta.get("LicenseUrl") or {}).get("value") or ""),
            "creator": _strip_html((meta.get("Artist") or {}).get("value") or "")[:120],
        })
    return out


def _commons_thumb(original: str, width: int) -> str:
    """upload.wikimedia.org/wikipedia/commons/a/ab/X.jpg -> .../commons/thumb/a/ab/X.jpg/500px-X.jpg"""
    m = re.match(r"(https://upload\.wikimedia\.org/wikipedia/commons)/(?!thumb/)([0-9a-f]/[0-9a-f]{2})/([^/?#]+)$", original or "")
    if not m:
        return original
    return f"{m.group(1)}/thumb/{m.group(2)}/{m.group(3)}/{width}px-{m.group(3)}"


_OV_LICENSE = {"cc0": "CC0", "pdm": "Public domain", "by": "CC BY", "by-sa": "CC BY-SA"}


def search_openverse(query: str, *, http: Callable = _http_json, limit: int = 20) -> List[Dict[str, Any]]:
    data = http("https://api.openverse.org/v1/images/", {
        "q": query, "license_type": "commercial,modification", "category": "photograph", "mature": "false",
        "page_size": limit,
    })
    out = []
    for r in (data or {}).get("results") or []:
        code = (r.get("license") or "").lower()
        if code not in _OV_LICENSE or r.get("mature"):
            continue
        lic = _OV_LICENSE[code] + (f" {r.get('license_version')}" if r.get("license_version") and code not in ("pdm",) else "")
        title = r.get("title") or ""
        if _BAD_TITLE.search(title) or (r.get("width") and r["width"] < 900):
            continue
        provider = (r.get("source") or r.get("provider") or "").replace("_", " ")
        out.append({
            "source": {"wikimedia": "Wikimedia Commons", "flickr": "Flickr"}.get(provider, provider.title() or "Openverse"),
            "title": title, "page_url": r.get("foreign_landing_url") or "", "image_url": r.get("url") or "",
            "thumb_url": r.get("thumbnail") or r.get("url") or "", "width": r.get("width"), "height": r.get("height"),
            "license": lic, "license_url": r.get("license_url") or "", "creator": (r.get("creator") or "")[:120],
        })
    return out


def candidates(queries: List[str], *, searchers: Optional[List[Callable]] = None, used: Optional[set] = None,
               errors: Optional[List[str]] = None, cap: int = 10) -> List[Dict[str, Any]]:
    """Photos for the queries from every source, deduplicated, landscape and large first."""
    searchers = searchers if searchers is not None else [search_commons, search_openverse]
    used = used or set()
    seen, out = set(), []
    for q in [q for q in queries if q and q.strip()][:3]:
        for s in searchers:
            try:
                for c in s(q.strip()):
                    key = c["image_url"]
                    if key and key not in seen and key not in used:
                        seen.add(key)
                        out.append(c)
            except Exception as e:  # noqa: BLE001
                if errors is not None:
                    errors.append(f"{getattr(s, '__name__', 'search')}('{q[:40]}'): {type(e).__name__}")

    def rank(c):
        w, h = c.get("width") or 0, c.get("height") or 1
        ratio = w / h if h else 0
        return (0 if 1.25 <= ratio <= 2.2 else 1, -min(w, 4000))
    out.sort(key=rank)
    return out[:cap]


_JUDGE = """You are the photo editor of MECE Insights, a long-form business magazine for Indian MBA students.
Article: "{title}"
This picture must show: {want}

Below are {n} candidate photographs, numbered 1 to {n} in order. Choose the ONE that shows this exact subject (the \
company, place, product, activity or setting named), is sharp, well lit and good enough to print large. Be strict: \
if none clearly shows the subject, choose none. Reject anything unrelated or merely generic, logos, maps, charts, \
screenshots, documents, images with large text, watermarks or borders, close-up portraits of an identifiable person, \
and anything sad, violent or sensitive.
Return ONLY JSON: {{"best": <number or null>, "why": "<one short sentence>"}}"""


def vision_models() -> List[str]:
    out = []
    try:
        from services.ai_providers import _GEMINI_LLM as default
    except Exception:
        default = "gemini-3.6-flash"
    for m in (os.getenv("DAILY_BLOG_VISION_MODEL"), os.getenv("GEMINI_MODEL"), default, "gemini-flash-latest"):
        m = (m or "").strip().removeprefix("models/")
        if m and m not in out and time.time() - _dead.get(m, 0) > 6 * 3600:
            out.append(m)
    return out


def gemini_vision(prompt: str, images: List[bytes]) -> str:
    from google.genai import types
    client = _client()
    parts: List[Any] = []
    for i, b in enumerate(images):
        parts += [f"Photo {i + 1}:", types.Part.from_bytes(data=b, mime_type="image/jpeg")]
    parts.append(prompt)
    last: Optional[Exception] = None
    for model in vision_models():
        try:
            resp = client.models.generate_content(
                model=model, contents=parts,
                config=types.GenerateContentConfig(response_mime_type="application/json", temperature=0.0))
            return resp.text or ""
        except Exception as e:  # noqa: BLE001
            last = e
            if _is_gone(e):
                _dead[model] = time.time()
    raise RuntimeError(f"no Gemini vision model answered: {type(last).__name__ if last else 'none configured'}")


def _thumb_jpeg(data: bytes, width: int = 480) -> bytes:
    from PIL import Image
    with Image.open(io.BytesIO(data)) as im:
        im = im.convert("RGB")
        if im.width > width:
            im = im.resize((width, round(im.height * width / im.width)))
        b = io.BytesIO()
        im.save(b, format="JPEG", quality=80)
        return b.getvalue()


def judge(cands: List[Dict[str, Any]], want: str, title: str, *, vision: Callable = gemini_vision,
          fetch: Callable = _http_bytes) -> Optional[Dict[str, Any]]:
    """The candidate the vision model says shows the subject, or None (strict: none is a valid answer)."""
    shown, thumbs = [], []
    for c in cands:
        try:
            thumbs.append(_thumb_jpeg(fetch(c["thumb_url"], 4_000_000)))
            shown.append(c)
        except Exception:
            continue
        if len(shown) >= 8:
            break
    if not shown:
        return None
    raw = vision(_JUDGE.format(title=title, want=want, n=len(shown)), thumbs)
    m = re.search(r"\{.*\}", raw or "", re.S)
    try:
        best = json.loads(m.group(0)).get("best") if m else None
    except ValueError:
        best = None
    if isinstance(best, str) and best.strip().isdigit():
        best = int(best.strip())
    if isinstance(best, (int, float)) and 1 <= int(best) <= len(shown):
        return shown[int(best) - 1]
    return None


def photo_credit(c: Dict[str, Any]) -> str:
    who = c.get("creator") or "Unknown photographer"
    return f"Photo: {who} / {c.get('source') or 'Wikimedia Commons'}, {c.get('license') or 'open licence'}"


def find_photo(item: Dict[str, Any], title: str, used: set, *, search: Callable = candidates,
               pick: Callable = judge, fetch: Callable = _http_bytes, errors: Optional[List[str]] = None
               ) -> Optional[Dict[str, Any]]:
    """{bytes, meta} for a real, openly licensed photo that shows this slot's subject, or None."""
    queries = [q for q in (item.get("search") or []) if isinstance(q, str)]
    if not queries and item.get("subject"):
        queries = [str(item["subject"])]
    if not queries:
        return None
    cands = search(queries, used=used, errors=errors)
    if not cands:
        if errors is not None:
            errors.append(f"no open-licensed photo found for: {', '.join(queries)[:120]}")
        return None
    want = str(item.get("subject") or item.get("alt") or item.get("prompt") or queries[0])[:300]
    try:
        best = pick(cands, want, title)
    except Exception as e:  # noqa: BLE001
        if errors is not None:
            errors.append(f"photo judge: {type(e).__name__}: {str(e)[:100]}")
        return None
    if not best:
        if errors is not None:
            errors.append(f"{len(cands)} photo(s) found for '{queries[0][:60]}', none showed the subject closely enough")
        return None
    data = fetch(best["image_url"])
    used.add(best["image_url"])
    return {"bytes": data, "meta": best}


# ============================================================================ storage
def to_web(data: bytes, width: int) -> Dict[str, Any]:
    """WebP for the page (resized to `width`) and a 1200 px JPEG for link previews, plus the page size."""
    from PIL import Image, ImageOps
    with Image.open(io.BytesIO(data)) as im:
        im = ImageOps.exif_transpose(im).convert("RGB")
        if im.width > width:
            im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
        w, h = im.size
        webp = io.BytesIO()
        try:
            im.save(webp, format="WEBP", quality=82, method=4)
            webp_bytes, webp_type = webp.getvalue(), "image/webp"
        except Exception:
            webp = io.BytesIO()
            im.save(webp, format="JPEG", quality=85, optimize=True, progressive=True)
            webp_bytes, webp_type = webp.getvalue(), "image/jpeg"
        # link previews (WhatsApp, LinkedIn, X) want a modest JPEG: 1200 px wide keeps it well under 300 KB
        og = im.resize((OG_WIDTH, round(h * OG_WIDTH / w)), Image.LANCZOS) if w > OG_WIDTH else im
        jpg = io.BytesIO()
        og.save(jpg, format="JPEG", quality=82, optimize=True, progressive=True)
        return {"web": webp_bytes, "web_type": webp_type, "jpeg": jpg.getvalue(), "width": w, "height": h}


_bucket_ready = {"ok": False}


def _ensure_bucket(supabase) -> None:
    if _bucket_ready["ok"]:
        return
    try:
        buckets = supabase.storage.list_buckets() or []
        names = [getattr(b, "name", None) or (b.get("name") if isinstance(b, dict) else None) for b in buckets]
        if BUCKET not in names:
            supabase.storage.create_bucket(BUCKET, options={"public": True})
        _bucket_ready["ok"] = True
    except Exception as e:  # noqa: BLE001 - the upload will say if it really is missing
        print(f"[insights images] bucket check: {type(e).__name__}: {e}")


def store(supabase, path: str, data: bytes, content_type: str) -> str:
    _ensure_bucket(supabase)
    st = supabase.storage.from_(BUCKET)
    st.upload(path, data, file_options={"content-type": content_type, "upsert": "true",
                                        "cache-control": "31536000"})
    url = st.get_public_url(path)
    return (url if isinstance(url, str) else (url or {}).get("publicUrl", "")).rstrip("?")


# ============================================================================ one article
def _save(supabase, slug: str, item: Dict[str, Any], role: str, n: int, data: bytes, *, upload: Callable,
          extra: Dict[str, Any]) -> Dict[str, Any]:
    web = to_web(data, HERO_WIDTH if role == "hero" else INLINE_WIDTH)
    tag = hashlib.sha1(data[:200_000]).hexdigest()[:8]
    ext = "webp" if web["web_type"] == "image/webp" else "jpg"
    url = upload(supabase, f"{slug}/{role}-{n}-{tag}.{ext}", web["web"], web["web_type"])
    res = {"url": url, "width": web["width"], "height": web["height"], "alt": (item.get("alt") or "")[:300],
           "caption": (item.get("caption") or "")[:300], **extra}
    if role == "hero":
        res["og_url"] = upload(supabase, f"{slug}/og-{tag}.jpg", web["jpeg"], "image/jpeg")
    else:
        res["after_section"] = int(item.get("after_section") or 1)
    return res


def make_images(supabase, slug: str, art: Dict[str, Any], *, title: str = "", generate: Callable = gemini_image,
                upload: Callable = store, photo: Callable = find_photo, order: Optional[List[str]] = None
                ) -> Dict[str, Any]:
    """{hero?, images: [...], errors: [...]} for an article's art direction. Never raises."""
    out: Dict[str, Any] = {"images": [], "errors": []}
    if not art:
        out["errors"].append("no art direction")
        return out
    order = order or picture_order()
    jobs = []
    if art.get("hero"):
        jobs.append(("hero", 0, art["hero"]))
    for i, item in enumerate((art.get("inline") or [])[:2]):
        jobs.append(("inline", i + 1, item))
    results: Dict[int, Dict[str, Any]] = {}

    # 1. real photos, one slot at a time so two slots never get the same photo
    if "photos" in order:
        used: set = set()
        for idx, (role, n, item) in enumerate(jobs):
            try:
                got = photo(item, title, used, errors=out["errors"])
                if got:
                    m = got["meta"]
                    results[idx] = _save(supabase, slug, item, role, n, got["bytes"], upload=upload, extra={
                        "credit": photo_credit(m), "credit_url": m.get("page_url") or "", "license": m.get("license"),
                        "license_url": m.get("license_url") or "", "source": "photo", "photo_title": m.get("title"),
                        "creator": m.get("creator") or "", "site": m.get("source") or ""})
            except Exception as e:  # noqa: BLE001
                out["errors"].append(f"{role} photo: {type(e).__name__}: {str(e)[:120]}")

    # 2. Gemini for the slots still empty (in parallel)
    gen_jobs = [(idx, j) for idx, j in enumerate(jobs) if idx not in results and (j[2].get("prompt") or "").strip()]
    if "gemini" in order and gen_jobs:
        if generate is gemini_image and not available():
            out["errors"].append("Gemini image generation not available (GEMINI_API_KEY)")
        else:
            lock = threading.Lock()

            def run(job):
                idx, (role, n, item) = job
                try:
                    g = generate(f"{item['prompt'].strip()}\n\n{HOUSE_STYLE}", "16:9" if role == "hero" else "3:2")
                    res = _save(supabase, slug, item, role, n, g["bytes"], upload=upload,
                                extra={"credit": CREDIT, "source": "gemini", "model": g.get("model")})
                    with lock:
                        results[idx] = res
                except Exception as e:  # noqa: BLE001
                    with lock:
                        out["errors"].append(f"{role} (Gemini): {type(e).__name__}: {str(e)[:200]}")

            with ThreadPoolExecutor(max_workers=3) as ex:
                list(ex.map(run, gen_jobs))

    for idx, (role, _n, _item) in enumerate(jobs):
        if idx in results:
            if role == "hero":
                out["hero"] = results[idx]
            else:
                out["images"].append(results[idx])
    out["images"].sort(key=lambda x: x.get("after_section", 1))
    return out


_ART_SYSTEM = """You are the picture editor of MECE Insights, a long-form business magazine for Indian MBA students. \
For the article below, plan three pictures: one hero and two inline. For each, first name what a REAL photograph \
should show (the actual company headquarters, plant, store, product, port, market, city, activity) and give 2-3 short \
search queries for Wikimedia Commons in English using proper names ("Bombay House Mumbai", "Jawaharlal Nehru Port \
container terminal", "UPI QR code shop India"). Then describe a scene for an AI image as a fallback: concrete, set \
in India, no text, logos, brands, charts or real people.
Return ONLY JSON: {"hero": {"subject": "what the photo must show", "search": ["query", "query"], "prompt": "fallback \
scene", "alt": "what the image shows", "caption": "one short sentence connecting the image to the story, no numbers"}, \
"inline": [{"after_section": 1, "subject": "...", "search": ["..."], "prompt": "...", "alt": "...", "caption": "..."}, \
{"after_section": 3, "subject": "...", "search": ["..."], "prompt": "...", "alt": "...", "caption": "..."}]}"""


def art_plan(chat: Callable, article: Dict[str, Any]) -> Dict[str, Any]:
    """Art direction for an article written without one (older posts)."""
    c = article.get("content") or {}
    brief = {"title": article.get("title"), "dek": article.get("dek"), "keywords": article.get("keywords"),
             "sections": [s.get("heading") for s in c.get("sections") or []],
             "lede": c.get("lede") or c.get("summary") or c.get("intro")}
    try:
        resp, _, _ = chat("seo_critique", messages=[{"role": "system", "content": _ART_SYSTEM},
                                                     {"role": "user", "content": json.dumps(brief, ensure_ascii=False)}],
                          response_format={"type": "json_object"}, temperature=0.4, max_tokens=900)
        txt = resp.choices[0].message.content or "{}"
        m = re.search(r"\{.*\}", txt, re.DOTALL)
        return json.loads(m.group(0)) if m else {}
    except Exception:
        return {}


# ============================================================================ diagnostics
def diagnose(supabase, *, generate: bool = True) -> Dict[str, Any]:
    """What works right now, for Admin -> Growth: photo search, the Gemini judge, generation, storage."""
    rep: Dict[str, Any] = {"order": picture_order(), "gemini_key": available()}
    errs: List[str] = []
    try:
        cs = candidates(["Gateway of India Mumbai"], errors=errs)
        rep["photo_search"] = {"ok": bool(cs), "found": len(cs), "errors": errs[:4],
                               "example": ({k: cs[0].get(k) for k in ("title", "source", "license", "page_url")} if cs else None)}
    except Exception as e:  # noqa: BLE001
        rep["photo_search"] = {"ok": False, "errors": [f"{type(e).__name__}: {str(e)[:160]}"]}
    if rep["gemini_key"]:
        try:
            rep["image_models"] = image_models()[:6]
        except Exception as e:  # noqa: BLE001
            rep["image_models"] = [f"list failed: {type(e).__name__}"]
        rep["vision_models"] = vision_models()
        if generate:
            try:
                g = gemini_image("A cup of masala chai on a wooden table by a window, morning light. " + HOUSE_STYLE, "1:1")
                rep["generation"] = {"ok": True, "model": g.get("model"), "bytes": len(g.get("bytes") or b"")}
            except Exception as e:  # noqa: BLE001
                rep["generation"] = {"ok": False, "error": str(e)[:600]}
    try:
        from PIL import Image
        b = io.BytesIO()
        Image.new("RGB", (8, 8), (200, 160, 120)).save(b, format="PNG")
        url = store(supabase, "_diagnostics/ping.png", b.getvalue(), "image/png")
        rep["storage"] = {"ok": bool(url), "bucket": BUCKET, "url": url}
    except Exception as e:  # noqa: BLE001
        rep["storage"] = {"ok": False, "bucket": BUCKET, "error": f"{type(e).__name__}: {str(e)[:200]}"}
    return rep
