"""
MECE Deck Vault Taxonomy & Controlled Vocabulary.

Extracted directly from the existing application (components/admin/deck-upload-manager.tsx,
database migrations 0007, 0008, 0041, 0042, 0047, 0049, 0050, and domain content).
"""

from typing import Dict, List, Set, Tuple

# Official CASE_TYPES / Domains from deck-upload-manager.tsx
CASE_TYPES: List[str] = [
    "strategy",
    "marketing",
    "finance",
    "operations",
    "supply chain",
    "product",
    "technology",
    "digital transformation",
    "analytics",
    "consulting",
    "market entry",
    "growth",
    "pricing",
    "M&A",
    "sustainability",
    "ESG",
    "hr",
    "general management",
    "social impact",
    "healthcare",
    "retail",
    "BFSI",
    "guesstimate",
    "other",
]

# Official RESULTS from deck-upload-manager.tsx
RESULTS: List[str] = [
    "National Winner",
    "National 1st Runner Up",
    "National 2nd Runner Up",
    "National Finalist",
    "National Semi Finalist",
    "Zonal Winner",
    "Zonal Runner Up",
    "Zonal Finalist",
    "Regional Winner",
    "Regional Finalist",
    "Campus Winner",
    "Campus Runner Up",
    "Campus Finalist",
    "Top 5",
    "Top 10",
    "Top 25",
    "Shortlisted",
    "Participant",
    "Problem Statement",
    "Template",
    "Other",
]

# Official ROUND_TYPES from deck-upload-manager.tsx
ROUND_TYPES: List[str] = [
    "screening",
    "campus",
    "zonal",
    "regional",
    "quarter-final",
    "semi-final",
    "final",
    "finale",
    "live-round",
    "case-submission",
    "problem-statement",
    "other",
]

# Official SOURCE_KINDS
SOURCE_KINDS: List[str] = ["corporate", "bschool"]

# Controlled Industries
INDUSTRIES: List[str] = [
    "FMCG",
    "Paints & Coatings",
    "E-Commerce & Retail",
    "BFSI & Banking",
    "Tech, SaaS & IT",
    "Automotive & Mobility",
    "Consumer Electronics",
    "Healthcare & Pharma",
    "Manufacturing & Industrial",
    "Energy, Oil & Gas",
    "Consulting & Professional Services",
    "Hospitality & Travel",
    "Telecommunications",
    "Media & Entertainment",
    "Agri-tech & Food Processing",
    "Logistics & Supply Chain",
    "Other",
]

# Controlled Business Functions
FUNCTIONS: List[str] = [
    "Strategy",
    "Marketing & Brand Strategy",
    "Operations & Supply Chain",
    "Finance & M&A",
    "Product Management",
    "Human Resources (HR)",
    "General Management",
    "Analytics & AI Strategy",
    "Go-To-Market & Sales",
]

# Controlled Difficulty Levels
DIFFICULTY_LEVELS: List[str] = ["easy", "medium", "hard"]

# Well-known Corporate & B-School Case Competitions & Hosts
KNOWN_COMPETITIONS: Dict[str, Dict[str, str]] = {
    "lime": {
        "canonical_name": "HUL L.I.M.E.",
        "organizer": "Hindustan Unilever",
        "company": "Hindustan Unilever",
        "source_kind": "corporate",
        "industry": "FMCG",
        "default_case_type": "marketing",
    },
    "canvas": {
        "canonical_name": "Asian Paints Canvas",
        "organizer": "Asian Paints",
        "company": "Asian Paints",
        "source_kind": "corporate",
        "industry": "Paints & Coatings",
        "default_case_type": "growth",
    },
    "edge": {
        "canonical_name": "Samsung E.D.G.E.",
        "organizer": "Samsung",
        "company": "Samsung",
        "source_kind": "corporate",
        "industry": "Consumer Electronics",
        "default_case_type": "product",
    },
    "interrobang": {
        "canonical_name": "ITC Interrobang?!",
        "organizer": "ITC Limited",
        "company": "ITC Limited",
        "source_kind": "corporate",
        "industry": "FMCG",
        "default_case_type": "strategy",
    },
    "steel-a-thon": {
        "canonical_name": "Tata Steel Steel-a-thon",
        "organizer": "Tata Steel",
        "company": "Tata Steel",
        "source_kind": "corporate",
        "industry": "Manufacturing & Industrial",
        "default_case_type": "operations",
    },
    "brandstorm": {
        "canonical_name": "L'Oréal Brandstorm",
        "organizer": "L'Oréal",
        "company": "L'Oréal",
        "source_kind": "corporate",
        "industry": "FMCG",
        "default_case_type": "marketing",
    },
    "loreal sustainability": {
        "canonical_name": "L'Oréal Sustainability Challenge",
        "organizer": "L'Oréal",
        "company": "L'Oréal",
        "source_kind": "corporate",
        "industry": "FMCG",
        "default_case_type": "sustainability",
    },
    "accenture b-school": {
        "canonical_name": "Accenture B-School Challenge",
        "organizer": "Accenture",
        "company": "Accenture",
        "source_kind": "corporate",
        "industry": "Consulting & Professional Services",
        "default_case_type": "digital transformation",
    },
    "transcend": {
        "canonical_name": "Colgate Transcend",
        "organizer": "Colgate-Palmolive",
        "company": "Colgate-Palmolive",
        "source_kind": "corporate",
        "industry": "FMCG",
        "default_case_type": "marketing",
    },
    "beat the curve": {
        "canonical_name": "ICICI Bank Beat The Curve",
        "organizer": "ICICI Bank",
        "company": "ICICI Bank",
        "source_kind": "corporate",
        "industry": "BFSI & Banking",
        "default_case_type": "BFSI",
    },
    "icici": {
        "canonical_name": "ICICI Bank Case Challenge",
        "organizer": "ICICI Bank",
        "company": "ICICI Bank",
        "source_kind": "corporate",
        "industry": "BFSI & Banking",
        "default_case_type": "BFSI",
    },
    "wavemakers": {
        "canonical_name": "boAt WaveMakers Challenge",
        "organizer": "boAt",
        "company": "boAt",
        "source_kind": "corporate",
        "industry": "Consumer Electronics",
        "default_case_type": "marketing",
    },
    "meesho": {
        "canonical_name": "Meesho Trust Challenge",
        "organizer": "Meesho",
        "company": "Meesho",
        "source_kind": "corporate",
        "industry": "E-Commerce & Retail",
        "default_case_type": "growth",
    },
    "myntra stylbiz": {
        "canonical_name": "Myntra StylBiz",
        "organizer": "Myntra",
        "company": "Myntra",
        "source_kind": "corporate",
        "industry": "E-Commerce & Retail",
        "default_case_type": "product",
    },
    "pidilite": {
        "canonical_name": "Bond with Pidilite Case Challenge",
        "organizer": "Pidilite Industries",
        "company": "Pidilite Industries",
        "source_kind": "corporate",
        "industry": "Manufacturing & Industrial",
        "default_case_type": "marketing",
    },
    "publicis sapient": {
        "canonical_name": "Publicis Sapient Product Spotlight",
        "organizer": "Publicis Sapient",
        "company": "Publicis Sapient",
        "source_kind": "corporate",
        "industry": "Tech, SaaS & IT",
        "default_case_type": "product",
    },
    "mmt": {
        "canonical_name": "MakeMyTrip Trek",
        "organizer": "MakeMyTrip",
        "company": "MakeMyTrip",
        "source_kind": "corporate",
        "industry": "Hospitality & Travel",
        "default_case_type": "product",
    },
    "flipkart wired": {
        "canonical_name": "Flipkart WiRED",
        "organizer": "Flipkart",
        "company": "Flipkart",
        "source_kind": "corporate",
        "industry": "E-Commerce & Retail",
        "default_case_type": "supply chain",
    },
    "marico over the wall": {
        "canonical_name": "Marico Over The Wall",
        "organizer": "Marico",
        "company": "Marico",
        "source_kind": "corporate",
        "industry": "FMCG",
        "default_case_type": "growth",
    },
    "mondelez": {
        "canonical_name": "Mondelez Supply Track",
        "organizer": "Mondelez International",
        "company": "Mondelez International",
        "source_kind": "corporate",
        "industry": "FMCG",
        "default_case_type": "supply chain",
    },
    "cummins": {
        "canonical_name": "Cummins Case Challenge",
        "organizer": "Cummins",
        "company": "Cummins",
        "source_kind": "corporate",
        "industry": "Manufacturing & Industrial",
        "default_case_type": "finance",
    },
    "union bank": {
        "canonical_name": "Union Bank Delphique Cerebro",
        "organizer": "Union Bank of India",
        "company": "Union Bank of India",
        "source_kind": "corporate",
        "industry": "BFSI & Banking",
        "default_case_type": "BFSI",
    },
    "tvs epic": {
        "canonical_name": "TVS Credit E.P.I.C. Challenge",
        "organizer": "TVS Credit",
        "company": "TVS Credit",
        "source_kind": "corporate",
        "industry": "BFSI & Banking",
        "default_case_type": "BFSI",
    },
    "galderma": {
        "canonical_name": "Galderma G.R.A.D. Challenge",
        "organizer": "Galderma",
        "company": "Galderma",
        "source_kind": "corporate",
        "industry": "Healthcare & Pharma",
        "default_case_type": "marketing",
    },
    "galderm": {
        "canonical_name": "Galderma G.R.A.D. Challenge",
        "organizer": "Galderma",
        "company": "Galderma",
        "source_kind": "corporate",
        "industry": "Healthcare & Pharma",
        "default_case_type": "marketing",
    },
    "lopreal": {
        "canonical_name": "L'Oréal Sustainability Challenge",
        "organizer": "L'Oréal",
        "company": "L'Oréal",
        "source_kind": "corporate",
        "industry": "FMCG",
        "default_case_type": "sustainability",
    },
    "publicis": {
        "canonical_name": "Publicis Sapient Product Spotlight",
        "organizer": "Publicis Sapient",
        "company": "Publicis Sapient",
        "source_kind": "corporate",
        "industry": "Tech, SaaS & IT",
        "default_case_type": "product",
    },
    "delphique": {
        "canonical_name": "Delphique National Management Convention",
        "organizer": "MDI Gurgaon",
        "company": "MDI Gurgaon",
        "source_kind": "bschool",
        "industry": "Consulting & Professional Services",
        "default_case_type": "strategy",
    },
    "kritva": {
        "canonical_name": "Kritva · Arthneeti",
        "organizer": "IMI New Delhi",
        "company": "IMI New Delhi",
        "source_kind": "bschool",
        "industry": "Consulting & Professional Services",
        "default_case_type": "strategy",
    },
}

# Top Indian Business Schools and Colleges
BSCHOOLS: Dict[str, str] = {
    "iima": "IIM Ahmedabad",
    "iim a": "IIM Ahmedabad",
    "iimb": "IIM Bangalore",
    "iim b": "IIM Bangalore",
    "iimc": "IIM Calcutta",
    "iim c": "IIM Calcutta",
    "iiml": "IIM Lucknow",
    "iim l": "IIM Lucknow",
    "iimk": "IIM Kozhikode",
    "iim k": "IIM Kozhikode",
    "iimi": "IIM Indore",
    "iim i": "IIM Indore",
    "iimm": "IIM Mumbai",
    "iim mumbai": "IIM Mumbai",
    "fms": "FMS Delhi",
    "xlri": "XLRI Jamshedpur",
    "spjimr": "SPJIMR Mumbai",
    "mdi": "MDI Gurgaon",
    "mdi gurgaon": "MDI Gurgaon",
    "iift": "IIFT Delhi",
    "sibm": "SIBM Pune",
    "nmims": "NMIMS Mumbai",
    "imi": "IMI New Delhi",
    "imi new delhi": "IMI New Delhi",
    "scmhrd": "SCMHRD Pune",
    "imt": "IMT Ghaziabad",
    "jbims": "JBIMS Mumbai",
    "tiss": "TISS Mumbai",
    "isb": "ISB Hyderabad",
}

# Standardized tag vocabulary
STANDARD_TAGS: Set[str] = {
    "Strategy",
    "Growth Strategy",
    "Go-to-Market",
    "GTM Strategy",
    "Marketing",
    "Brand Strategy",
    "Rural Marketing",
    "Distribution",
    "Channel Strategy",
    "Pricing",
    "Supply Chain",
    "Logistics",
    "Digital Transformation",
    "Product Management",
    "Market Entry",
    "Customer Acquisition",
    "Customer Retention",
    "Unit Economics",
    "Sustainability",
    "ESG",
    "Circular Economy",
    "Fintech",
    "Financial Inclusion",
    "Omnichannel",
    "E-Commerce",
    "D2C",
    "B2B Sales",
    "Contractor Ecosystem",
    "Cost Optimization",
    "M&A Integration",
}
