"""Render migrations/0001_interview_intel.sql from the SQLAlchemy models.

The models are the single source of truth; this script makes the SQL idempotent
(IF NOT EXISTS everywhere) and appends the isolation footer (role, grants, RLS).

    python -m scripts.generate_migration > migrations/0001_interview_intel.sql
"""

from __future__ import annotations

import sys

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from interview_intelligence.db.models import SCHEMA, Base

HEADER = f"""-- =====================================================================================
-- MECE Interview Intelligence — schema `{SCHEMA}` (v1)
-- GENERATED by scripts/generate_migration.py from interview_intelligence/db/models.py.
-- Do not hand-edit the CREATE statements; change the models and regenerate.
--
-- Idempotent: safe to run more than once (CREATE ... IF NOT EXISTS, guarded DO blocks).
-- Run with a role that may create schemas (Supabase SQL editor = postgres role).
--
-- Isolation (spec §1/§63): this schema is NOT one of Supabase's PostgREST exposed
-- schemas, grants nothing to anon/authenticated, and has RLS enabled on every table with a
-- single permissive policy scoped TO ii_service. The II service connects directly with its
-- own login role `ii_service`; no other non-owner role can read or write these tables.
-- =====================================================================================

CREATE SCHEMA IF NOT EXISTS {SCHEMA};
"""

FOOTER = f"""
-- ---------------------------------------------------------------------------------------
-- Isolation footer
-- ---------------------------------------------------------------------------------------
-- 1) Dedicated login role for the II service (set its password OUTSIDE this file:
--      ALTER ROLE ii_service WITH PASSWORD '<generated secret>';
--    then build II_DATABASE_URL with it).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ii_service') THEN
    CREATE ROLE ii_service LOGIN NOINHERIT;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA {SCHEMA} TO ii_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {SCHEMA} TO ii_service;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA {SCHEMA} TO ii_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA {SCHEMA}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ii_service;

-- 2) Nothing for the browser-facing Supabase roles. (Guarded: the roles only exist on Supabase.)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'REVOKE ALL ON SCHEMA {SCHEMA} FROM anon';
    EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA {SCHEMA} FROM anon';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'REVOKE ALL ON SCHEMA {SCHEMA} FROM authenticated';
    EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA {SCHEMA} FROM authenticated';
  END IF;
END
$$;

-- 3) Defence in depth: RLS on every table. The only policy is `ii_service_all`, scoped
--    TO ii_service, so any other role that is not the table owner (and does not have
--    BYPASSRLS) sees no rows even if a grant is added by mistake later.
DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = '{SCHEMA}' LOOP
    EXECUTE format('ALTER TABLE {SCHEMA}.%I ENABLE ROW LEVEL SECURITY', t.tablename);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE schemaname = '{SCHEMA}' AND tablename = t.tablename
        AND policyname = 'ii_service_all'
    ) THEN
      EXECUTE format(
        'CREATE POLICY ii_service_all ON {SCHEMA}.%I FOR ALL TO ii_service USING (true) WITH CHECK (true)',
        t.tablename);
    END IF;
  END LOOP;
END
$$;
"""


def render() -> str:
    dialect = postgresql.dialect()
    out = [HEADER]
    for table in Base.metadata.sorted_tables:
        ddl = str(CreateTable(table, if_not_exists=True).compile(dialect=dialect)).strip()
        out.append(ddl + ";\n")
        for idx in sorted(table.indexes, key=lambda i: i.name or ""):
            out.append(str(CreateIndex(idx, if_not_exists=True).compile(dialect=dialect)).strip() + ";\n")
    out.append(FOOTER)
    return "\n".join(out)


if __name__ == "__main__":
    sys.stdout.write(render())
