-- =====================================================================================
-- MECE Interview Intelligence — schema `interview_intel` (v1)
-- GENERATED by scripts/generate_migration.py from interview_intelligence/db/models.py.
-- Do not hand-edit the CREATE statements; change the models and regenerate.
--
-- Idempotent: safe to run more than once (CREATE ... IF NOT EXISTS, guarded DO blocks).
-- Run with a role that may create schemas (Supabase SQL editor = postgres role).
--
-- Isolation (spec §1/§63): this schema is NOT one of Supabase's PostgREST exposed
-- schemas, grants nothing to anon/authenticated, and has RLS enabled on every table with a
-- single permissive policy scoped TO ii_service. The II service connects directly with its
-- own login role `ii_service`; no other non-owner role can read or write these tables.
-- =====================================================================================

CREATE SCHEMA IF NOT EXISTS interview_intel;

CREATE TABLE IF NOT EXISTS interview_intel.access_grants (
	id UUID NOT NULL, 
	email_lc VARCHAR(320) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	grant_type VARCHAR(16) NOT NULL, 
	note TEXT NOT NULL, 
	granted_by VARCHAR(320) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_access_grants PRIMARY KEY (id), 
	CONSTRAINT ck_access_grants_status CHECK (status IN ('enabled', 'disabled')), 
	CONSTRAINT uq_access_grants_email_lc UNIQUE (email_lc)
);

CREATE TABLE IF NOT EXISTS interview_intel.audit_logs (
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	actor_user_id UUID, 
	actor_email VARCHAR(320) NOT NULL, 
	action VARCHAR(64) NOT NULL, 
	target_type VARCHAR(64) NOT NULL, 
	target_id VARCHAR(128) NOT NULL, 
	meta JSONB NOT NULL, 
	CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_action ON interview_intel.audit_logs (action);

CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at ON interview_intel.audit_logs (created_at);

CREATE TABLE IF NOT EXISTS interview_intel.drive_folders (
	id UUID NOT NULL, 
	scope_key VARCHAR(64) NOT NULL, 
	kind VARCHAR(16) NOT NULL, 
	folder_id VARCHAR(128) NOT NULL, 
	parent_folder_id VARCHAR(128) NOT NULL, 
	name VARCHAR(128) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_drive_folders PRIMARY KEY (id), 
	CONSTRAINT uq_drive_folders_scope_key_kind UNIQUE (scope_key, kind)
);

CREATE TABLE IF NOT EXISTS interview_intel.evaluation_runs (
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	kind VARCHAR(24) NOT NULL, 
	evaluator_version VARCHAR(32) NOT NULL, 
	prompt_versions JSONB NOT NULL, 
	dataset_version VARCHAR(32) NOT NULL, 
	metrics JSONB NOT NULL, 
	results JSONB NOT NULL, 
	baseline_run_id UUID, 
	notes TEXT NOT NULL, 
	CONSTRAINT pk_evaluation_runs PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS interview_intel.jobs (
	id UUID NOT NULL, 
	kind VARCHAR(48) NOT NULL, 
	payload JSONB NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	attempts INTEGER NOT NULL, 
	max_attempts INTEGER NOT NULL, 
	run_after TIMESTAMP WITH TIME ZONE NOT NULL, 
	locked_at TIMESTAMP WITH TIME ZONE, 
	locked_by VARCHAR(64) NOT NULL, 
	last_error TEXT NOT NULL, 
	dedupe_key VARCHAR(160), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_jobs PRIMARY KEY (id), 
	CONSTRAINT ck_jobs_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'dead')), 
	CONSTRAINT uq_jobs_dedupe_key UNIQUE (dedupe_key)
);

CREATE INDEX IF NOT EXISTS ix_jobs_status_run_after ON interview_intel.jobs (status, run_after);

CREATE TABLE IF NOT EXISTS interview_intel.model_runs (
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	user_id UUID, 
	session_id UUID, 
	stage VARCHAR(48) NOT NULL, 
	provider VARCHAR(32) NOT NULL, 
	model VARCHAR(96) NOT NULL, 
	prompt_id VARCHAR(64) NOT NULL, 
	prompt_version VARCHAR(32) NOT NULL, 
	schema_version VARCHAR(32) NOT NULL, 
	input_tokens INTEGER NOT NULL, 
	output_tokens INTEGER NOT NULL, 
	cost_usd NUMERIC(12, 6) NOT NULL, 
	latency_ms INTEGER NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	attempt INTEGER NOT NULL, 
	error TEXT NOT NULL, 
	validation JSONB NOT NULL, 
	CONSTRAINT pk_model_runs PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_model_runs_created_at ON interview_intel.model_runs (created_at);

CREATE INDEX IF NOT EXISTS ix_model_runs_session_id ON interview_intel.model_runs (session_id);

CREATE INDEX IF NOT EXISTS ix_model_runs_stage_created ON interview_intel.model_runs (stage, created_at);

CREATE TABLE IF NOT EXISTS interview_intel.questions (
	id UUID NOT NULL, 
	origin VARCHAR(16) NOT NULL, 
	role_family VARCHAR(64) NOT NULL, 
	competency_ids JSONB NOT NULL, 
	question_type VARCHAR(32) NOT NULL, 
	difficulty INTEGER NOT NULL, 
	text TEXT NOT NULL, 
	text_hash VARCHAR(64) NOT NULL, 
	meta JSONB NOT NULL, 
	quality_status VARCHAR(16) NOT NULL, 
	times_selected INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_questions PRIMARY KEY (id), 
	CONSTRAINT uq_questions_text_hash UNIQUE (text_hash)
);

CREATE INDEX IF NOT EXISTS ix_questions_role_family ON interview_intel.questions (role_family);

CREATE TABLE IF NOT EXISTS interview_intel.system_config (
	key VARCHAR(128) NOT NULL, 
	value JSONB NOT NULL, 
	updated_by VARCHAR(320) NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_system_config PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS interview_intel.users (
	id UUID NOT NULL, 
	email VARCHAR(320) NOT NULL, 
	email_lc VARCHAR(320) NOT NULL, 
	last_tier VARCHAR(16) NOT NULL, 
	last_entitled BOOLEAN NOT NULL, 
	last_access_via VARCHAR(32), 
	drive_folder_key VARCHAR(64), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_users PRIMARY KEY (id), 
	CONSTRAINT uq_users_drive_folder_key UNIQUE (drive_folder_key)
);

CREATE INDEX IF NOT EXISTS ix_users_email_lc ON interview_intel.users (email_lc);

CREATE TABLE IF NOT EXISTS interview_intel.company_profiles (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	company_name VARCHAR(200) NOT NULL, 
	company_name_lc VARCHAR(200) NOT NULL, 
	facts JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_company_profiles PRIMARY KEY (id), 
	CONSTRAINT fk_company_profiles_user_id_users FOREIGN KEY(user_id) REFERENCES interview_intel.users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_company_profiles_company_name_lc ON interview_intel.company_profiles (company_name_lc);

CREATE INDEX IF NOT EXISTS ix_company_profiles_user_id ON interview_intel.company_profiles (user_id);

CREATE TABLE IF NOT EXISTS interview_intel.documents (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	kind VARCHAR(8) NOT NULL, 
	source VARCHAR(16) NOT NULL, 
	label VARCHAR(200) NOT NULL, 
	file_name VARCHAR(255) NOT NULL, 
	mime_type VARCHAR(128) NOT NULL, 
	ext VARCHAR(8) NOT NULL, 
	size_bytes INTEGER NOT NULL, 
	sha256 VARCHAR(64) NOT NULL, 
	text_sha256 VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	page_count INTEGER, 
	text_chars INTEGER NOT NULL, 
	text_quality JSONB NOT NULL, 
	parse_status VARCHAR(16) NOT NULL, 
	parse_error TEXT NOT NULL, 
	injection_flags JSONB NOT NULL, 
	storage_status VARCHAR(16) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_documents PRIMARY KEY (id), 
	CONSTRAINT ck_documents_kind CHECK (kind IN ('cv', 'jd')), 
	CONSTRAINT ck_documents_parse_status CHECK (parse_status IN ('pending', 'parsed', 'unreadable', 'failed')), 
	CONSTRAINT ck_documents_storage_status CHECK (storage_status IN ('pending', 'uploading', 'synced', 'failed', 'disabled', 'deleted')), 
	CONSTRAINT fk_documents_user_id_users FOREIGN KEY(user_id) REFERENCES interview_intel.users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_documents_dedupe ON interview_intel.documents (user_id, kind, sha256);

CREATE INDEX IF NOT EXISTS ix_documents_text_hash ON interview_intel.documents (user_id, kind, text_sha256);

CREATE INDEX IF NOT EXISTS ix_documents_user_kind ON interview_intel.documents (user_id, kind);

CREATE TABLE IF NOT EXISTS interview_intel.drive_files (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	target_kind VARCHAR(16) NOT NULL, 
	target_id VARCHAR(64) NOT NULL, 
	drive_file_id VARCHAR(128), 
	drive_folder_id VARCHAR(128), 
	file_name VARCHAR(255) NOT NULL, 
	mime_type VARCHAR(128) NOT NULL, 
	sha256 VARCHAR(64) NOT NULL, 
	storage_status VARCHAR(16) NOT NULL, 
	attempts INTEGER NOT NULL, 
	last_error TEXT NOT NULL, 
	uploaded_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_drive_files PRIMARY KEY (id), 
	CONSTRAINT ck_drive_files_storage_status CHECK (storage_status IN ('pending', 'uploading', 'synced', 'failed', 'disabled', 'deleted')), 
	CONSTRAINT uq_drive_files_target_kind_target_id UNIQUE (target_kind, target_id), 
	CONSTRAINT fk_drive_files_user_id_users FOREIGN KEY(user_id) REFERENCES interview_intel.users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_drive_files_user_id ON interview_intel.drive_files (user_id);

CREATE TABLE IF NOT EXISTS interview_intel.document_analyses (
	id UUID NOT NULL, 
	document_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	kind VARCHAR(8) NOT NULL, 
	sha256 VARCHAR(64) NOT NULL, 
	analysis_version VARCHAR(32) NOT NULL, 
	prompt_version VARCHAR(32) NOT NULL, 
	model VARCHAR(96) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	result JSONB NOT NULL, 
	quality JSONB NOT NULL, 
	error TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_document_analyses PRIMARY KEY (id), 
	CONSTRAINT uq_document_analyses_document_id_analysis_version UNIQUE (document_id, analysis_version), 
	CONSTRAINT ck_document_analyses_status CHECK (status IN ('pending', 'running', 'ready', 'failed', 'unreadable')), 
	CONSTRAINT fk_document_analyses_document_id_documents FOREIGN KEY(document_id) REFERENCES interview_intel.documents (id) ON DELETE CASCADE, 
	CONSTRAINT fk_document_analyses_user_id_users FOREIGN KEY(user_id) REFERENCES interview_intel.users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_document_analyses_user_id ON interview_intel.document_analyses (user_id);

CREATE TABLE IF NOT EXISTS interview_intel.document_contents (
	document_id UUID NOT NULL, 
	blob_enc BYTEA, 
	text_enc BYTEA, 
	redacted_text_enc BYTEA, 
	key_id VARCHAR(32) NOT NULL, 
	purged_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_document_contents PRIMARY KEY (document_id), 
	CONSTRAINT fk_document_contents_document_id_documents FOREIGN KEY(document_id) REFERENCES interview_intel.documents (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS interview_intel.interview_sessions (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	status_reason TEXT NOT NULL, 
	cv_document_id UUID NOT NULL, 
	jd_document_id UUID NOT NULL, 
	company_profile_id UUID, 
	source_session_id UUID, 
	config JSONB NOT NULL, 
	mode VARCHAR(32) NOT NULL, 
	difficulty VARCHAR(16) NOT NULL, 
	duration_minutes INTEGER NOT NULL, 
	role_family VARCHAR(64) NOT NULL, 
	role_title VARCHAR(200) NOT NULL, 
	company_name VARCHAR(200) NOT NULL, 
	pre_interview_summary JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE, 
	last_activity_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	paused_at TIMESTAMP WITH TIME ZONE, 
	ended_at TIMESTAMP WITH TIME ZONE, 
	ended_reason VARCHAR(32) NOT NULL, 
	active_seconds INTEGER NOT NULL, 
	assessment_status VARCHAR(16) NOT NULL, 
	assessment_confidence VARCHAR(16) NOT NULL, 
	cost_usd NUMERIC(12, 6) NOT NULL, 
	versions JSONB NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_interview_sessions PRIMARY KEY (id), 
	CONSTRAINT ck_interview_sessions_status CHECK (status IN ('created', 'uploading', 'analyzing', 'ready', 'active', 'paused', 'completed', 'abandoned', 'expired', 'failed')), 
	CONSTRAINT ck_interview_sessions_assessment_status CHECK (assessment_status IN ('none', 'pending', 'processing', 'ready', 'partial', 'failed')), 
	CONSTRAINT fk_interview_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES interview_intel.users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_interview_sessions_cv_document_id_documents FOREIGN KEY(cv_document_id) REFERENCES interview_intel.documents (id), 
	CONSTRAINT fk_interview_sessions_jd_document_id_documents FOREIGN KEY(jd_document_id) REFERENCES interview_intel.documents (id), 
	CONSTRAINT fk_interview_sessions_company_profile_id_company_profiles FOREIGN KEY(company_profile_id) REFERENCES interview_intel.company_profiles (id)
);

CREATE INDEX IF NOT EXISTS ix_interview_sessions_mode ON interview_intel.interview_sessions (mode);

CREATE INDEX IF NOT EXISTS ix_interview_sessions_user_created ON interview_intel.interview_sessions (user_id, created_at);

CREATE INDEX IF NOT EXISTS ix_interview_sessions_user_status ON interview_intel.interview_sessions (user_id, status);

CREATE TABLE IF NOT EXISTS interview_intel.claims (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	claim_key VARCHAR(16) NOT NULL, 
	source VARCHAR(16) NOT NULL, 
	text TEXT NOT NULL, 
	claim_type VARCHAR(32) NOT NULL, 
	slots JSONB NOT NULL, 
	priority INTEGER NOT NULL, 
	verification_status VARCHAR(32) NOT NULL, 
	exchange_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_claims PRIMARY KEY (id), 
	CONSTRAINT uq_claims_session_id_claim_key UNIQUE (session_id, claim_key), 
	CONSTRAINT fk_claims_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_claims_session_id ON interview_intel.claims (session_id);

CREATE TABLE IF NOT EXISTS interview_intel.competency_assessments (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	competency_id VARCHAR(96) NOT NULL, 
	canonical_competency_id VARCHAR(96) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	category VARCHAR(32) NOT NULL, 
	importance VARCHAR(16) NOT NULL, 
	evidence_state VARCHAR(32) NOT NULL, 
	score INTEGER, 
	band VARCHAR(32) NOT NULL, 
	confidence VARCHAR(16) NOT NULL, 
	confidence_basis JSONB NOT NULL, 
	rationale TEXT NOT NULL, 
	evidence_refs JSONB NOT NULL, 
	strengths JSONB NOT NULL, 
	gaps JSONB NOT NULL, 
	missing_evidence JSONB NOT NULL, 
	anomaly_flags JSONB NOT NULL, 
	evaluator_version VARCHAR(32) NOT NULL, 
	rubric_hash VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_competency_assessments PRIMARY KEY (id), 
	CONSTRAINT uq_competency_assessments_session_id_competency_id UNIQUE (session_id, competency_id), 
	CONSTRAINT ck_competency_assessments_evidence_state CHECK (evidence_state IN ('strong', 'moderate', 'weak', 'contradictory', 'not_sufficiently_tested')), 
	CONSTRAINT fk_competency_assessments_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_competency_assessments_session_id ON interview_intel.competency_assessments (session_id);

CREATE TABLE IF NOT EXISTS interview_intel.competency_history (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	competency_id VARCHAR(96) NOT NULL, 
	canonical_competency_id VARCHAR(96) NOT NULL, 
	role_family VARCHAR(64) NOT NULL, 
	score INTEGER, 
	evidence_state VARCHAR(32) NOT NULL, 
	confidence VARCHAR(16) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_competency_history PRIMARY KEY (id), 
	CONSTRAINT uq_competency_history_session_id_competency_id UNIQUE (session_id, competency_id), 
	CONSTRAINT fk_competency_history_user_id_users FOREIGN KEY(user_id) REFERENCES interview_intel.users (id) ON DELETE CASCADE, 
	CONSTRAINT fk_competency_history_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_competency_history_user_comp ON interview_intel.competency_history (user_id, canonical_competency_id);

CREATE TABLE IF NOT EXISTS interview_intel.feedback_items (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	kind VARCHAR(16) NOT NULL, 
	category VARCHAR(48) NOT NULL, 
	severity VARCHAR(16) NOT NULL, 
	competency_ids JSONB NOT NULL, 
	title VARCHAR(300) NOT NULL, 
	body JSONB NOT NULL, 
	qa_status VARCHAR(16) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_feedback_items PRIMARY KEY (id), 
	CONSTRAINT fk_feedback_items_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_feedback_items_category ON interview_intel.feedback_items (category);

CREATE INDEX IF NOT EXISTS ix_feedback_items_session_id ON interview_intel.feedback_items (session_id);

CREATE TABLE IF NOT EXISTS interview_intel.interview_blueprints (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	role_profile JSONB NOT NULL, 
	competency_model JSONB NOT NULL, 
	rubric JSONB NOT NULL, 
	rubric_hash VARCHAR(64) NOT NULL, 
	blueprint JSONB NOT NULL, 
	qa_report JSONB NOT NULL, 
	engine_versions JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_interview_blueprints PRIMARY KEY (id), 
	CONSTRAINT uq_interview_blueprints_session_id UNIQUE (session_id), 
	CONSTRAINT fk_interview_blueprints_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS interview_intel.interview_events (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	type VARCHAR(48) NOT NULL, 
	payload JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_interview_events PRIMARY KEY (id), 
	CONSTRAINT fk_interview_events_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_interview_events_session_id ON interview_intel.interview_events (session_id);

CREATE TABLE IF NOT EXISTS interview_intel.interview_exchanges (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	seq INTEGER NOT NULL, 
	planned_qid VARCHAR(32) NOT NULL, 
	section_id VARCHAR(32) NOT NULL, 
	question_text TEXT NOT NULL, 
	question_meta JSONB NOT NULL, 
	competency_ids JSONB NOT NULL, 
	difficulty INTEGER NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	probes INTEGER NOT NULL, 
	live_signals JSONB NOT NULL, 
	metrics JSONB NOT NULL, 
	evidence_status VARCHAR(16) NOT NULL, 
	analysis JSONB NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	closed_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_interview_exchanges PRIMARY KEY (id), 
	CONSTRAINT uq_interview_exchanges_session_id_seq UNIQUE (session_id, seq), 
	CONSTRAINT fk_interview_exchanges_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_interview_exchanges_session_id ON interview_intel.interview_exchanges (session_id);

CREATE TABLE IF NOT EXISTS interview_intel.interview_messages (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	seq INTEGER NOT NULL, 
	role VARCHAR(16) NOT NULL, 
	kind VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	exchange_id UUID, 
	action VARCHAR(32) NOT NULL, 
	client_turn_id VARCHAR(64), 
	meta JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_interview_messages PRIMARY KEY (id), 
	CONSTRAINT uq_interview_messages_session_id_seq UNIQUE (session_id, seq), 
	CONSTRAINT uq_interview_messages_session_id_client_turn_id UNIQUE (session_id, client_turn_id), 
	CONSTRAINT ck_interview_messages_role CHECK (role IN ('interviewer', 'candidate', 'system')), 
	CONSTRAINT fk_interview_messages_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_interview_messages_session_id ON interview_intel.interview_messages (session_id);

CREATE TABLE IF NOT EXISTS interview_intel.interview_states (
	session_id UUID NOT NULL, 
	version INTEGER NOT NULL, 
	state JSONB NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_interview_states PRIMARY KEY (session_id), 
	CONSTRAINT fk_interview_states_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS interview_intel.reports (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	report JSONB NOT NULL, 
	report_version VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_reports PRIMARY KEY (id), 
	CONSTRAINT uq_reports_session_id UNIQUE (session_id), 
	CONSTRAINT fk_reports_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS interview_intel.evidence_items (
	id UUID NOT NULL, 
	session_id UUID NOT NULL, 
	exchange_id UUID NOT NULL, 
	ref VARCHAR(16) NOT NULL, 
	competency_id VARCHAR(96) NOT NULL, 
	sub_competency VARCHAR(160) NOT NULL, 
	evidence_type VARCHAR(32) NOT NULL, 
	polarity VARCHAR(16) NOT NULL, 
	strength VARCHAR(16) NOT NULL, 
	quote TEXT NOT NULL, 
	quote_verified BOOLEAN NOT NULL, 
	interpretation TEXT NOT NULL, 
	ownership VARCHAR(16) NOT NULL, 
	cv_consistency VARCHAR(16) NOT NULL, 
	confidence FLOAT NOT NULL, 
	extractor_version VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_evidence_items PRIMARY KEY (id), 
	CONSTRAINT fk_evidence_items_session_id_interview_sessions FOREIGN KEY(session_id) REFERENCES interview_intel.interview_sessions (id) ON DELETE CASCADE, 
	CONSTRAINT fk_evidence_items_exchange_id_interview_exchanges FOREIGN KEY(exchange_id) REFERENCES interview_intel.interview_exchanges (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_evidence_items_competency_id ON interview_intel.evidence_items (competency_id);

CREATE INDEX IF NOT EXISTS ix_evidence_items_exchange_id ON interview_intel.evidence_items (exchange_id);

CREATE INDEX IF NOT EXISTS ix_evidence_items_session_id ON interview_intel.evidence_items (session_id);


-- ---------------------------------------------------------------------------------------
-- Isolation footer
-- ---------------------------------------------------------------------------------------
-- 1) Dedicated login role for the II service (set its password OUTSIDE this file:
--      ALTER ROLE ii_service WITH PASSWORD '<generated secret>';
--    then build II_DATABASE_URL with it).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ii_service') THEN
    CREATE ROLE ii_service LOGIN NOINHERIT;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA interview_intel TO ii_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA interview_intel TO ii_service;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA interview_intel TO ii_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA interview_intel
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ii_service;

-- 2) Nothing for the browser-facing Supabase roles. (Guarded: the roles only exist on Supabase.)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'REVOKE ALL ON SCHEMA interview_intel FROM anon';
    EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA interview_intel FROM anon';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'REVOKE ALL ON SCHEMA interview_intel FROM authenticated';
    EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA interview_intel FROM authenticated';
  END IF;
END
$$;

-- 3) Defence in depth: RLS on every table. The only policy is `ii_service_all`, scoped
--    TO ii_service, so any other role that is not the table owner (and does not have
--    BYPASSRLS) sees no rows even if a grant is added by mistake later.
DO $$
DECLARE t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'interview_intel' LOOP
    EXECUTE format('ALTER TABLE interview_intel.%I ENABLE ROW LEVEL SECURITY', t.tablename);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE schemaname = 'interview_intel' AND tablename = t.tablename
        AND policyname = 'ii_service_all'
    ) THEN
      EXECUTE format(
        'CREATE POLICY ii_service_all ON interview_intel.%I FOR ALL TO ii_service USING (true) WITH CHECK (true)',
        t.tablename);
    END IF;
  END LOOP;
END
$$;
